[JB][OPS-14337] (#138)
* [JB][OPS-14337]
- reset order if email or billing address are changed after journey is in sent state

* [JB][OPS-14337] create journey clone, i.e. a new journey when trying again from cancelled/failed pages

* bump up pay-api cor version

* fix compilation error: illegal variable in pattern alternative

* fix compilation error: unused import

* update sbt-scoverage plugin: -> 2.4.2